sudo: false
language: python

python: "3.6"

services:
  - postgresql

env:
  - DJANGO=2.0 DB=postgresql

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database experiments_db;' -U postgres
  - psql -c 'create database experiments_test_db;' -U postgres

script:
  - python app_server/manage.py test
