sudo: false
language: python
cache: pip
python: "3.6"

services:
  - postgresql

env:
  - DJANGO=2.0 DB=postgresql

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database experiments_db;' -U postgres
  - psql -c "CREATE USER toto PASSWORD 'azert';" -U postgres
  - psql -c "ALTER USER toto CREATEDB;" -U postgres
  - psql -c "ALTER USER toto WITH SUPERUSER;" -U postgres

script:
  - python app_server/manage.py test
  - pytest