sudo: false
language: python

python: "3.6"

services:
  - mysql
env:
  - DJANGO=2.0 DB=mysql

install:
  - pip install -r requirements.txt

before_script:
   - mysql -e 'create database test;' -u root

script:
  - python app_server/manage.py test
